### ISSUE TITLE
Pop interface convention

### ISSUE THREAD

**Issue by countvajhula** [lehitoskin/typed-stack#5]
Hi there,
I was looking for a stack implementation in Racket and came across this one. Just wondering, is there a reason why the [`pop`](https://docs.racket-lang.org/typed-stack/index.html#%28def._%28%28lib._typed-stack%2Fmain..rkt%29._pop%29%29) function doesn't return the popped value but instead only the new stack, or `Void` in case of a mutative `pop!`? This would mean that in order to access the top element and pop it off, you'd have to first `top` and then `pop`, is that right? I'm not familiar with Typed Racket so it's very possible there's a good reason for this, but for what it's worth, usually with `pop` for stack implementations, the convention seems to be to return the element that's been popped off (for instance in [python](https://docs.python.org/3/tutorial/datastructures.html#using-lists-as-stacks) and [ruby](https://ruby-doc.org/core-2.2.0/Array.html#method-i-pop)).

To be closer to this convention, how about returning two [values](https://docs.racket-lang.org/reference/values.html#%28def._%28%28quote._~23~25kernel%29._values%29%29) instead - the popped element, and the new stack? In the case of the mutative `pop!` it could return just the popped element instead of Void.

**Comment by lehitoskin** [comment]
`pop` only returning the top can be considered an error and `pop!` only returning `Void` can be changed. Having `values` would be more useful for `pop`, I think.

**Comment by countvajhula** [comment]
Looks great, thanks! 😄 🥇
