### ISSUE TITLE
Useful printed representation

### ISSUE THREAD

**Issue by countvajhula** [lehitoskin/typed-stack#6]
At the moment the stack prints as `#<Stack>` in the REPL, so the contents aren't immediately apparent without inspecting it. Consider making the `Stack` struct type [`#:transparent`](https://docs.racket-lang.org/guide/define-struct.html?q=transparent#%28tech._transparent%29), or providing another useful printed representation via [gen:custom-write](https://docs.racket-lang.org/reference/Printer_Extension.html#%28def._%28%28lib._racket%2Fprivate%2Fbase..rkt%29._gen~3acustom-write%29%29).

**Comment by lehitoskin** [comment]
`stack->string` exists, but `#:transparent` sounds useful, too.
